version: "3.8"

services:
  app:
    # The image name will be overridden by the GitHub Actions workflow.  If you run
    # locally you can build and tag your own image and update the value here.
    image: ghcr.io/${REPOSITORY_OWNER:-your-ghcr-username}/fortstack-intern:latest
    container_name: todo-app
    ports:
      - "4000:4000"
    # Load environment variables from the `.env` file in the same directory
    env_file:
      - .env
    # Fallback environment variable so the container still starts if `mongoDbUrl`
    # is missing from the .env file
    environment:
      - mongoDbUrl=${mongoDbUrl}
    # Healthcheck to ensure the application is responding on port 4000
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:4000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    # Label used by watchtower to identify which containers to monitor for updates
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  # Watchtower monitors running containers and automatically restarts them when a
  # new image is available in the registry.  It uses the label on the `app`
  # service to decide which containers to watch.
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=300
    restart: unless-stopped